---
title: "oneKP: An R package for accessing 1KP project data"
authors:
- affiliation: 1
  name: Zebulun Arendsee 
  orcid: 0000-0002-5833-798X
- affiliation: 1
  name: Eve Wurtele
  orcid: XXXX-XXXX-XXXX-XXXX
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: yes
bibliography: paper.bib
tags:
- R
- transcriptomics
- plants
affiliations:
  - index: 1
    name: Iowa State University, Department of Genetics Development and Cell Biology
---


# Summary

The 1000 Plants initiative provides the transcriptome sequences to over 1000
plants from diverse lineages [@matasci2014data]. This package provides an R
interface to the project metadata and raw sequence data.

The metadata for each transcriptome project is scraped from the 1KP project
website (https://sites.google.com/a/ualberta.ca/onekp/). This metadata includes
the species, tissue, and research group for each sequence sample. `oneKP`
leverages the taxonomy program `taxizedb` [@taxizedb], a local database version
of `taxize` [@taxize], to allow filtering of the metadata by taxonomic group
(entered as either a taxon name or NCBI ID). The raw nucleotide or translated
peptide sequence can then be downloaded for the full, or filtered, table of
transcriptom projects. 


# Related work

An alternative to using this `oneKP` package is to access the data directly
through CyVerse (previously iPlant) [@goff2011iplant]. CyVerse efficiently
distributes data using the iRODS data system [@rajasekar2010irods]. This
approach is preferable for high-throughput cases or in where iRODS is in play.
Further, accessing data straight from the source at CyVerse is more stable than
scraping it from project website. However, the `oneKP` R package is generally
easier to use (no iRODS dependency or CyVerse API) and offers powerful
filtering solutions. 


# Funding

This material is based upon work supported by the National Science Foundation under Grant No. IOS 1546858

# References
